### PR TITLE
chore(CI): Cache cargo dependencies

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit 8b187a6 has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit 8b187a6 with merge 017e297...

**Comment by ghost** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/badboy/test-project/builds/126366652)

**Pull request merged**
