### PR TITLE
chore(CI): Simply run semantic-rs

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit 875a9fa has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit 875a9fa with merge d38fa36...

**Comment by ghost** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/badboy/test-project/builds/126373275)

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:bangbang: Invalid head SHA found, retrying: `0000000000000000000000000000000000000000`

**Comment by ghost** [comment]
:pushpin: Commit b7782ae has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit b7782ae with merge d6e7887...

**Comment by ghost** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/badboy/test-project/builds/126376833)

**Pull request merged**
