### PR TITLE
chore: GitHub webhook gives status, maybe Travis is not needed

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by badboy** [comment]
@homu r+

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit cabced4 has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit cabced4 with merge c1a8305...

**Comment by badboy** [comment]
@not-a-robot retry

**Comment by ghost** [comment]
:hourglass: Testing commit cabced4 with merge 8bc2c56...

**Comment by badboy** [comment]
@not-a-robot retry

**Comment by ghost** [comment]
:hourglass: Testing commit cabced4 with merge f0a01f1...

**Comment by badboy** [comment]
@not-a-robot retry

**Comment by ghost** [comment]
:hourglass: Testing commit cabced4 with merge 45fdb24...

**Comment by ghost** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/badboy/test-project/builds/123545312)

**Pull request merged**
