### PR TITLE
feat: Math mode

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit 01e014a has been approved by `badboy`

**Comment by badboy** [comment]
@not-a-robot r-

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit 01e014a has been approved by `badboy`

**Comment by badboy** [comment]
@not-a-robot retry

**Comment by ghost** [comment]
:hourglass: Testing commit 01e014a with merge b51963c...

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit 24afa46 has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit 24afa46 with merge 9fdfed5...

**Comment by ghost** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/badboy/test-project/builds/126381331)

**Pull request merged**
