### PR TITLE
chore: Enable homu webhook

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit abe9dd9 has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit abe9dd9 with merge 95f1d36...

**Comment by ghost** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/badboy/test-project/builds/123392993)

**Pull request merged**
